Dependencies:
- 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcoreaddons' : '@latest-kf6'
    'frameworks/kio' : '@latest-kf6'
    'network/kio-extras': '@latest-kf6'
